name: Create Resourcepack

on:

  # Manual workflow trigger
  workflow_dispatch: {}

  push:
    branches:
    - main
    paths:
    - 'assets/**'
    - 'pack.mcmeta'
    - 'pack.png'

jobs:
  auto-resourcepack:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'Dream-of-Wolf/Resourcepacks' ||
      contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Package & Optimize Resourcepack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: .
          #options_file: Resource-Pack.zip

          #Setting
          zip_spec_conformance_level: disregard
          size_increasing_zip_obfuscation: true

      - name: DownloadArtifact
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Crate version
        id: version
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          files: ./pack.zip
