name: Create ResourcePack

on:
  push:
    branches:
    - main
    paths:
    - 'assets/**'
    - 'pack.mcmeta'
    - 'pack.png'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'Dream-of-Wolf/Resourcepacks'

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@master

      - name: Crate version
        id: version
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Package resourcepack
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'Resource-Pack.zip'
          exclusions: '*.git* .github* README.md'

      - name: Create Release
        id: release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: ${{ steps.version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Resourcepack
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }} 
          asset_path: ./Resource-Pack.zip
          asset_name: Resource-Pack-${{ steps.version.outputs.new_tag }}.zip
          asset_content_type: application/zip
